//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTierMovie.DAL.Context.imdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string Rank { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Description { get; set; }
        public string Director { get; set; }
        public string Actors { get; set; }
        public int Year { get; set; }
        public int Runtime_Minutes { get; set; }
        public double Rating { get; set; }
        public int Votes { get; set; }
        public string Revenue_Millions { get; set; }
        public Nullable<int> Metascore { get; set; }
    }
}
